#!/usr/bin/env bash

RCLONE_BWLIMIT="###MAX_BANDWIDTH###"
RCLONE_CONFIG=""
RCLONE_LOG_LEVEL="###LOG_LEVEL###"
RCLONE_SFTP_HOST="###SFTP_HOST###"
RCLONE_SFTP_KEY_FILE=/dev/shm/ssh-key
RCLONE_SFTP_KNOWN_HOSTS_FILE="###SSH_KNOWN_HOSTS_FILE###"
RCLONE_SFTP_PORT="###SFTP_PORT###"
RCLONE_SFTP_USER="###SFTP_USER###"
RCLONE_STATS="10m"
RCLONE_STATS_ONE_LINE="true"
TZ="###TZ###"

REMOTE_DOWNLOAD_DIR="###REMOTE_DOWNLOAD_DIR###"
REMOTE_UPLOAD_DIR="###REMOTE_UPLOAD_DIR###"

export RCLONE_BWLIMIT RCLONE_CONFIG RCLONE_LOG_LEVEL RCLONE_SFTP_HOST RCLONE_SFTP_KEY_FILE \
    RCLONE_SFTP_KNOWN_HOSTS_FILE RCLONE_SFTP_PORT RCLONE_SFTP_USER RCLONE_STATS \
    RCLONE_STATS_ONE_LINE TZ
